/* CombiQuest · Game engine and views: stages, quest map, battle */
const S=[{n:3,name:'Permuter',r:0,gen:()=>gc(1)},{n:4,name:'Combiner',r:0,gen:()=>gc(2)},{n:5,name:'Factorial Titan',r:0,boss:1,t:30,gen:()=>gc(3)},
{n:3,name:'Roost',r:1,gen:gp},{n:2,name:'The Vault',r:1,t:0,gen:gd},{n:5,name:'Flock King',r:1,boss:1,t:25,gen:gp},
{n:3,name:'Loop',r:2,gen:()=>gr('p',1)},{n:4,name:'Roots',r:2,gen:()=>gr(R(0,1)?'root':'p',2)},{n:5,name:'Fibonacci Wyrm',r:2,boss:1,t:35,gen:()=>gr(R(0,1)?'root':'p',3)}];
const RN=['COUNTING','PIGEONHOLE','RECURRENCE'],POS=[[200,60],[110,135],[200,210],[290,285],[200,360],[110,435],[200,510],[290,585],[200,660]],HEART=5;
function drawMap(){const nx=S.findIndex((_,i)=>!P.best[i]);let h='<svg id="mapsvg" viewBox="0 0 400 730">';
for(let i=0;i<8;i++)h+='<line x1="'+POS[i][0]+'" y1="'+POS[i][1]+'" x2="'+POS[i+1][0]+'" y2="'+POS[i+1][1]+'" stroke="'+(P.best[i]?'var(--acc)':'var(--ln)')+'" stroke-width="2" stroke-dasharray="'+(P.best[i]?'0':'5 5')+'"/>';
S.forEach((s,i)=>{const[x,y]=POS[i],z=s.boss?30:22,lk=i>0&&!P.best[i-1],b=P.best[i]||0,left=x>=290,c='var(--r'+s.r+')';
if(i%3==0)h+='<text class="rl" x="'+(x<200?x+36:x>200?x-36:x+40)+'" y="'+(y-24)+'" fill="'+c+'" text-anchor="'+(x>200?'end':'start')+'">'+RN[s.r]+'</text>';
h+='<g class="nd'+(lk?' lk':b?' cl':i==nx?' nx':'')+'" style="--c:'+c+'" '+(lk?'':'onclick="start('+i+')"')+'><circle cx="'+x+'" cy="'+y+'" r="'+(z-2)+'"/><text x="'+x+'" y="'+(y+4)+'">'+(s.boss?'★':i+1)+'</text></g>';
h+='<text class="lab" x="'+(left?x-z-8:x+z+8)+'" y="'+(y-2)+'" text-anchor="'+(left?'end':'start')+'">'+s.name+'</text><text class="lab" x="'+(left?x-z-8:x+z+8)+'" y="'+(y+14)+'" text-anchor="'+(left?'end':'start')+'" fill="var(--acc)">'+(b?'♥'.repeat(b)+'♡'.repeat(HEART-b):'')+'</text>'});
h+='</svg>';const tot=Object.values(P.best).reduce((a,b)=>a+b,0),pw=P.pw;
h='<div class="stats"><span>♥ '+tot+' / 45</span><span>'+Object.keys(P.best).length+' / 9 cleared</span></div><div class="pn" style="padding:8px">'+h+'</div>';$('#map').innerHTML=h}
function ice(r,boss){const c='var(--r'+r+')',bd=['60,8 108,34 108,86 60,112 12,86 12,34','60,10 112,60 60,110 8,60','60,6 82,38 114,44 92,70 98,106 60,90 22,106 28,70 6,44 38,38'][r];
return '<svg id="ice" viewBox="0 0 120 120"><polygon points="'+bd+'" fill="none" stroke="'+c+'" stroke-width="4"/><polygon points="'+bd+'" fill="'+c+'" opacity=".16"/>'+(boss?'<circle cx="60" cy="60" r="56" fill="none" stroke="'+c+'" stroke-dasharray="6 6" stroke-width="2"/><path d="M30 18l8 14M90 18l-8 14" stroke="'+c+'" stroke-width="4"/>':'')+'<rect x="34" y="52" width="52" height="14" fill="'+c+'"/><rect x="54" y="48" width="12" height="22" fill="var(--bg)"/><path d="M36 84h48M44 92h32" stroke="'+c+'" stroke-width="3"/></svg>'}
let B=null,TM=null;
function show(v){['map','bat','lab','theory','tests'].forEach(x=>{$('#'+x).hidden=x!=v});const nv={map:'nm',bat:'nm',lab:'nw',theory:'nt',tests:'ne'}[v];['nm','nw','nt','ne'].forEach(i=>$('#'+i).classList.toggle('on',i==nv));if(v!='bat'){clearInterval(TM);B=null}if(v=='map')drawMap();if(v=='tests')renderTests();window.scrollTo(0,0)}
function start(i){const s=S[i];B={i,s,hp:s.n,hearts:HEART,combo:0,gain:0,lock:false,frz:0};
$('#bat').innerHTML='<div class="top"><button onclick="show(\'map\')">← Back</button><div class="hearts" id="hr"></div><div class="sm" id="cb"></div></div><div class="arena '+(s.boss?'boss':'')+'" style="--rc:var(--r'+s.r+')">'+ice(s.r,s.boss)+'<div class="hp" id="pp"></div><div class="sm" style="margin-top:6px"><b style="color:var(--r'+s.r+')">'+s.name+'</b></div></div><div class="pn"><div class="tb" id="tb" style="visibility:hidden"><i></i></div><div class="q" id="qq"></div><div id="qa"></div><div class="pw"><button id="pf"></button><button id="ph"></button><button id="ps"></button></div><div class="out" id="fb"></div></div>';
$('#pf').onclick=()=>use('f');$('#ph').onclick=()=>use('h');$('#ps').onclick=()=>use('s');show('bat');nextQ()}
function hud(){$('#hr').innerHTML='♥'.repeat(B.hearts)+'<s>'+'♥'.repeat(HEART-B.hearts)+'</s>';$('#cb').textContent=B.combo>1?'COMBO ×'+B.combo:'';$('#pp').innerHTML=Array.from({length:B.s.n},(_,i)=>'<i class="'+(i>=B.hp?'off':'')+'"></i>').join('');
[['f','FREEZE'],['h','HINT'],['s','SKIP']].forEach(([k,n])=>{const b=$('#p'+k);b.textContent=n+' ×'+P.pw[k];b.disabled=P.pw[k]<1||B.lock||(k=='f'&&!(B.s.t!==0))})}
function use(k){if(B.lock||P.pw[k]<1)return;P.pw[k]--;save();
if(k=='f'){B.frz=10;$('#fb').innerHTML='<div class="good">Frozen · 10s</div>'}
if(k=='h')$('#fb').innerHTML='<div class="good">Hint: '+B.cur.h+'</div>';
if(k=='s'){B.lock=true;clearInterval(TM);$('#fb').innerHTML='<div class="sm">Skipped</div>';hud();return setTimeout(nextQ,500)}hud()}
function nextQ(){if(B.hp<=0)return win();B.lock=false;B.frz=0;B.cur=B.s.gen();$('#fb').innerHTML='';$('#qq').textContent=B.cur.q;
if(B.cur.drop){$('#qa').innerHTML='<div class="bxs" id="bxs"></div>';drawD()}else{
$('#qa').innerHTML='<input id="in" autocomplete="off" placeholder="Your answer" '+(matchMedia('(pointer:coarse)').matches?'inputmode="none"':'inputmode="numeric"')+'><div class="kp">'+['7','8','9','4','5','6','1','2','3','−','0','⌫'].map(k=>'<button data-k="'+k+'">'+k+'</button>').join('')+'</div><div class="row"><button class="pri" id="go">Attack</button></div>';
$('#go').onclick=sub;$('#in').onkeydown=e=>{if(e.key=='Enter')sub()};document.querySelectorAll('.kp button').forEach(b=>b.onclick=()=>{const i=$('#in'),k=b.dataset.k;sfx.tick();i.value=k=='⌫'?i.value.slice(0,-1):i.value+(k=='−'?'-':k)});if(!matchMedia('(pointer:coarse)').matches)$('#in').focus()}
clearInterval(TM);const t=B.s.t===0?0:(B.s.t||45);$('#tb').style.visibility=t?'visible':'hidden';hud();
if(t){let l=t;$('#tb i').style.width='100%';TM=setInterval(()=>{if(B.frz>0){B.frz-=.1;return}l-=.1;$('#tb i').style.width=Math.max(0,l/t*100)+'%';$('#tb i').style.background=l<t*.25?'var(--red)':'var(--ok)';if(l<=0){clearInterval(TM);miss('Time up. ')}},100)}}
function sub(){if(B.lock)return;const v=$('#in').value.trim().replace('−','-');if(!v)return;if(!/^-?\d+$/.test(v)){$('#fb').innerHTML='<div class="bad">Enter a whole number (digits only).</div>';return}v==B.cur.a?hitM():miss('Wrong ('+v+'). ')}
function hitM(){B.lock=true;clearInterval(TM);B.hp--;B.combo++;const dm=(10+B.combo*2)*(B.s.boss?2:1);B.gain+=dm;sfx.ok();pop('+'+dm);const m=$('#ice');m.classList.remove('hit');void m.offsetWidth;m.classList.add('hit');$('#fb').innerHTML='<div class="good">Hit! Working:</div>'+B.cur.s.map(x=>'<div>'+x+'</div>').join('');hud();if(B.hp<=0)setTimeout(()=>m.classList.add('die'),350);setTimeout(nextQ,B.hp<=0?1600:2000)}
function miss(pre){if(B.lock)return;B.lock=true;clearInterval(TM);B.hearts--;B.combo=0;sfx.bad();document.body.classList.add('sh');setTimeout(()=>document.body.classList.remove('sh'),320);hud();
$('#fb').innerHTML='<div class="bad">'+pre+'−1 ♥ · Here is how:</div>'+B.cur.s.map(x=>'<div>'+x+'</div>').join('')+'<div class="row"><button class="pri" id="ct">'+'Continue'+'</button></div>';$('#ct').onclick=()=>B.hearts?nextQ():lose()}
function drawD(){const d=B.cur.drop;$('#bxs').innerHTML=d.c.map((c,i)=>'<div class="bx'+(c>=d.m?' hit':'')+'" data-i="'+i+'"><b>#'+(i+1)+' · '+c+'</b>'+'<span class="dt"></span>'.repeat(c)+'</div>').join('');
document.querySelectorAll('.bx').forEach(b=>b.onclick=()=>{if(B.lock)return;const i=+b.dataset.i;d.c[i]++;d.n++;sfx.tick();drawD();$('#fb').innerHTML='<div>Drop '+d.n+' · fullest box '+Math.max(...d.c)+' (⌈'+d.n+'/'+d.k+'⌉ = '+Math.ceil(d.n/d.k)+')</div>';
if(d.c[i]>=d.m){const bd=d.k*(d.m-1)+1;d.n==bd?hitM():miss('Tripped at drop '+d.n+' (target '+bd+'). ')}})}
function win(){clearInterval(TM);sfx.win();const i=B.i,st=B.hearts,first=!P.best[i];let rw='';if(first){P.xp+=B.gain;P.hs.push({n:S[i].name,xp:B.gain});P.hs.sort((a,b)=>b.xp-a.xp);P.hs=P.hs.slice(0,5)}
P.best[i]=Math.max(P.best[i]||0,st);if(B.s.boss&&first){const k='fhs'[R(0,2)];P.pw[k]++;rw='<p class="good">Loot: +1 '+{f:'FREEZE',h:'HINT',s:'SKIP'}[k]+'</p>'}save();paint();
$('#ov').innerHTML='<div class="ov"><div class="pn"><div class="big" style="color:var(--acc)">Stage clear</div><div class="hearts">'+'♥'.repeat(st)+'<s>'+'♥'.repeat(HEART-st)+'</s></div><p>'+S[i].name+' · '+(first?'+'+B.gain+' XP':'replay · no new XP')+'</p>'+rw+'<div class="row">'+(i<8?'<button class="pri" onclick="go('+(i+1)+')">Next</button>':'')+'<button onclick="cl()">Map</button></div></div></div>';confetti()}
function lose(){$('#ov').innerHTML='<div class="ov"><div class="pn" style="border-left-color:var(--red)"><div class="big bad">Game over</div><p>Out of hearts. Check the working and try again.</p><div class="row"><button class="pri" onclick="go('+B.i+')">Retry</button><button onclick="cl()">Map</button></div></div></div>'}
const cl=()=>{$('#ov').innerHTML='';show('map')},go=i=>{$('#ov').innerHTML='';start(i)};
